const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
let M=[],BM=[],S=[],MMS=[],TM=[],LAST=0;
const mgr=(s,i)=>(s.mms&&s.mms[i])||s.mm,defTm=()=>TM.includes(LAST)?LAST:(TM.at(-1)??0);
const PAL=['#1f9d55','#6cc491','#f0642f','#0e6b3a','#3b82f6','#e5a00d','#d946a8','#14b8a6','#8b5cf6','#64748b','#ef4444','#84cc16','#0ea5e9','#c084fc','#f59e0b'];
const $$$=n=>'$'+Math.round(n).toLocaleString('en-US'),K=n=>Math.abs(n)>=1e6?'$'+(n/1e6).toFixed(2)+'M':Math.abs(n)>=1e3?'$'+(n/1e3).toFixed(1)+'K':'$'+Math.round(n);
const sum=a=>a.reduce((x,y)=>x+y,0),pct=(a,b)=>b?((a-b)/b*100):null;
const tg=(o)=>Array.isArray(o)?o:null;
const st={page:'sales',from:0,to:0,mm:'all',q:'',gq:'',sort:{sales:['sales',-1],bonus:['bonus',-1],tgt:['gap',1],trf:['cAvg',-1]},pg:{sales:0,bonus:0,tgt:0,trf:0},tm:0,tstat:'all',bmm:new Set(),bfrom:0,bto:0};
let charts=[];
const css=v=>getComputedStyle(document.documentElement).getPropertyValue(v).trim();
function chart(id,cfg){const el=$('#'+id);if(!el)return;const g=css('--bd'),m=css('--mut');Chart.defaults.color=m;Chart.defaults.font.family='Inter';
 cfg.options=Object.assign({responsive:true,maintainAspectRatio:false,animation:{duration:900,easing:'easeOutQuart'},interaction:{mode:'index',intersect:false},plugins:{legend:{position:'bottom',labels:{usePointStyle:true,boxWidth:8}}}},cfg.options||{});
 if(cfg.type!=='doughnut'){cfg.options.scales=Object.assign({x:{grid:{display:false}},y:{grid:{color:g},ticks:{callback:v=>K(v)}}},cfg.options.scales||{})}
 charts.push(new Chart(el,cfg))}
function count(){$$('[data-c]').forEach(e=>{const t=+e.dataset.c,f=e.dataset.f,t0=performance.now();(function s(n){const p=Math.min(1,(n-t0)/900),v=t*(1-Math.pow(1-p,3));e.textContent=f==='k'?K(v):f==='p'?v.toFixed(1)+'%':f==='d'?v.toFixed(1):f==='t'?'$'+v.toFixed(2):Math.round(v).toLocaleString();if(p<1)requestAnimationFrame(s)})(t0)})}
const match=s=>{const q=(st.gq+' '+st.q).trim().toLowerCase().split(/\s+/).filter(Boolean);const h=(s.name+' '+s.mm).toLowerCase();return q.every(w=>h.includes(w))};
const kpi=(ic,t,v,f,sub)=>`<div class="card kpi"><div class="t"><span class="ic">${ic}</span>${t}</div><div class="v" data-c="${v}" data-f="${f}">0</div><div class="t">${sub}</div></div>`;
const delta=(c,p)=>{const d=pct(c,p);return d==null?'<span class="mut">no prior data</span>':`<span class="${d>=0?'up':'dn'}">${d>=0?'▲':'▼'} ${Math.abs(d).toFixed(1)}%</span> vs previous month`};
const opts=(a,sel)=>a.map((x,i)=>`<option value="${i}" ${i==sel?'selected':''}>${x}</option>`).join('');
const spark=a=>{const mx=Math.max(...a,1),w=70,h=22,p=a.map((v,i)=>`${i*w/(a.length-1)},${h-v/mx*h}`).join(' ');return `<svg width="${w}" height="${h}"><polyline fill="none" stroke="var(--pr)" stroke-width="1.6" points="${p}"/></svg>`};
const csv=(rows,name)=>{const t=rows.map(r=>r.map(c=>`"${String(c).replace(/"/g,'""')}"`).join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([t],{type:'text/csv'}));a.download=name;a.click()};
const status=(s,i)=>{const m=s.mo[i],t=tg(m.t),a=i<LAST?m.f:(m.p||m.f);if(!t||!a)return['n/a','b-na',null,null];return a>=t[1]?['Above max','b-ok',a/t[0]*100,a-t[0]]:a>=t[0]?['On target','b-ok',a/t[0]*100,a-t[0]]:['Below target','b-bad',a/t[0]*100,a-t[0]]};
function table(id,cols,rows,foot){const[k,d]=st.sort[id],c=cols.find(x=>x.k===k)||cols[0];rows=[...rows].sort((a,b)=>{const x=c.v(a),y=c.v(b);return(typeof x==='string'?x.localeCompare(y):(x??-1e15)-(y??-1e15))*d});
 const n=15,pages=Math.max(1,Math.ceil(rows.length/n));st.pg[id]=Math.min(st.pg[id],pages-1);const sl=rows.slice(st.pg[id]*n,st.pg[id]*n+n);
 return{rows,html:`<div class="tw"><table><thead><tr>${cols.map(x=>`<th class="${x.n?'n':''}" data-t="${id}" data-k="${x.k}">${x.h}${x.k===k?(d>0?' ↑':' ↓'):''}</th>`).join('')}</tr></thead><tbody>${sl.map(r=>`<tr class="clk" data-s="${r.id}">${cols.map(x=>`<td class="${x.n?'n':''}">${x.r?x.r(r):x.v(r)}</td>`).join('')}</tr>`).join('')||`<tr><td colspan="${cols.length}" class="empty">No stores match these filters. Clear a filter or search term.</td></tr>`}</tbody>${foot?`<tfoot><tr>${foot(rows)}</tr></tfoot>`:''}</table></div>
 <div class="pg"><span>${rows.length} stores · page ${st.pg[id]+1} of ${pages}</span><div><button class="btn" data-pg="${id}" data-d="-1">Prev</button><button class="btn" data-pg="${id}" data-d="1">Next</button></div></div>`}}
const range=(id)=>`<div class="f">From<select data-r="${id}f">${opts(id==='s'?M:BM,id==='s'?st.from:st.bfrom)}</select></div><div class="f">To<select data-r="${id}t">${opts(id==='s'?M:BM,id==='s'?st.to:st.bto)}</select></div>`;
const mmSel=`<div class="f">Area MM<select data-mm><option value="all">All MMs</option>${MMS.map(m=>`<option ${st.mm===m?'selected':''}>${m}</option>`).join('')}</select></div>`;
/* ---------- TARGETS & SALES ---------- */
function sales(){const A=S.filter(s=>(st.mm==='all'||s.mm===st.mm)),idx=[...Array(st.to-st.from+1)].map((_,i)=>st.from+i);
 const tot=(fn,list=A)=>idx.map(i=>sum(list.map(s=>fn(s.mo[i]))));const F=tot(m=>m.f),B=tot(m=>m.b),P=tot(m=>m.p);
 const act=idx.map(i=>A.filter(s=>s.mo[i].f>0).length),last=F.length-1;
 const cv=(s,i,k)=>s.mo[i][k]>0?s.mo[i][k]:null,av=a=>{a=a.filter(x=>x!=null);return a.length?sum(a)/a.length:null};
 const CU=idx.map(i=>av(A.map(s=>cv(s,i,'c')))),TK=idx.map(i=>av(A.map(s=>cv(s,i,'tk'))));
 while(last>0&&!F[last])break;
 const sales$=sum(F),bon$=sum(B),lastI=(()=>{let l=F.length-1;while(l>0&&!F[l])l--;return l})();
 const list=A.filter(match).map(s=>{const f=idx.map(i=>s.mo[i].f),b=sum(idx.map(i=>s.mo[i].b));return{...s,f,sales:sum(f),bonus:b,bp:sum(f)?b/sum(f)*100:0,last:f[lastI]||0,mom:pct(f[lastI],f[lastI-1]),spk:f}}).filter(s=>s.sales>0||s.bonus>0);
 const cols=[{k:'name',h:'Store',v:s=>s.name},{k:'mm',h:'MM',v:s=>s.mm},{k:'sales',h:'Sales',n:1,v:s=>s.sales,r:s=>$$$(s.sales)},{k:'bonus',h:'Bonus paid',n:1,v:s=>s.bonus,r:s=>$$$(s.bonus)},{k:'bp',h:'Bonus %',n:1,v:s=>s.bp,r:s=>s.bp.toFixed(2)+'%'},{k:'last',h:M[idx[lastI]],n:1,v:s=>s.last,r:s=>$$$(s.last)},{k:'mom',h:'MoM',n:1,v:s=>s.mom,r:s=>s.mom==null?'–':`<span class="${s.mom>=0?'up':'dn'}">${s.mom>=0?'▲':'▼'} ${Math.abs(s.mom).toFixed(1)}%</span>`},{k:'spk',h:'Trend',v:s=>s.spk.at(-1),r:s=>spark(s.spk)}];
 const T=table('sales',cols,list,r=>`<td>Total (${r.length})</td><td></td><td class="n">${$$$(sum(r.map(x=>x.sales)))}</td><td class="n">${$$$(sum(r.map(x=>x.bonus)))}</td><td></td><td></td><td></td><td></td>`);
 // targets Sep/Oct
 const ti=st.tm,tl=A.filter(s=>match(s)&&tg(s.mo[ti].t)).map(s=>{const[l,c,pc,gap]=status(s,ti),t=tg(s.mo[ti].t);return{...s,tmin:t[0],tmax:t[1],bmin:tg(s.mo[ti].bv)?.[0]||0,bmax:tg(s.mo[ti].bv)?.[1]||0,proj:ti<LAST?s.mo[ti].f:(s.mo[ti].p||s.mo[ti].f),label:l,cls:c,ach:pc,gap}}).filter(s=>st.tstat==='all'||s.label===st.tstat);
 const tc=[{k:'name',h:'Store',v:s=>s.name},{k:'mm',h:'MM',v:s=>s.mm},{k:'tmin',h:'Target range',n:1,v:s=>s.tmin,r:s=>K(s.tmin)+' – '+K(s.tmax)},{k:'bmin',h:'Bonus range',n:1,v:s=>s.bmin,r:s=>$$$(s.bmin)+' – '+$$$(s.bmax)},{k:'proj',h:'Actual / projected',n:1,v:s=>s.proj,r:s=>$$$(s.proj)},{k:'ach',h:'% of min target',n:1,v:s=>s.ach,r:s=>s.ach==null?'–':`<div style="display:flex;gap:8px;align-items:center;justify-content:flex-end"><span>${s.ach.toFixed(0)}%</span><div class="pill"><i style="width:${Math.min(100,s.ach)}%"></i></div></div>`},{k:'gap',h:'Gap to min',n:1,v:s=>s.gap,r:s=>s.gap==null?'–':`<span class="${s.gap>=0?'up':'dn'}">${s.gap>=0?'+':'−'}${$$$(Math.abs(s.gap))}</span>`},{k:'label',h:'Status',v:s=>s.label,r:s=>`<span class="badge ${s.cls}">${s.label}</span>`}];
 const TT=table('tgt',tc,tl);const cnt=l=>tl.filter(s=>s.label===l).length;
 const tmA=TM.map(i=>{const x=A.filter(s=>tg(s.mo[i].t));return{i,min:sum(x.map(s=>s.mo[i].t[0])),max:sum(x.map(s=>s.mo[i].t[1])),p:sum(x.map(s=>s.mo[i].p)),n:x.length}});
 const rowsM=idx.map((i,k)=>{const top=[...A].sort((a,b)=>b.mo[i].f-a.mo[i].f)[0];return`<tr><td>${M[i]}</td><td class="n">${act[k]}</td><td class="n">${$$$(F[k])}</td><td class="n">${P[k]?$$$(P[k]):'–'}</td><td class="n">${$$$(B[k])}</td><td class="n">${F[k]?(B[k]/F[k]*100).toFixed(2)+'%':'–'}</td><td class="n">${k&&F[k-1]&&F[k]?`<span class="${F[k]>=F[k-1]?'up':'dn'}">${(pct(F[k],F[k-1])).toFixed(1)}%</span>`:'–'}</td><td class="n">${act[k]&&F[k]?$$$(F[k]/act[k]):'–'}</td><td class="n">${CU[k]!=null?CU[k].toFixed(1):'–'}</td><td class="n">${TK[k]!=null?'$'+TK[k].toFixed(2):'–'}</td><td>${top&&top.mo[i].f?top.name:'–'}</td></tr>`}).join('');
 const mmT=MMS.map(m=>({m,v:sum(idx.map(i=>sum(S.filter(s=>mgr(s,i)===m).map(s=>s.mo[i].f))))})).filter(x=>x.v>0).sort((a,b)=>b.v-a.v);
 const top=[...list].sort((a,b)=>b.sales-a.sales).slice(0,10);
 
 const trL=A.filter(match).map(s=>{const c=idx.map(i=>cv(s,i,'c')),t=idx.map(i=>cv(s,i,'tk'));return{...s,cAvg:av(c),tAvg:av(t),cLast:c[lastI],tLast:t[lastI],cMom:c[lastI]&&c[lastI-1]?pct(c[lastI],c[lastI-1]):null,tMom:t[lastI]&&t[lastI-1]?pct(t[lastI],t[lastI-1]):null,cs:c.map(v=>v||0),ts:t.map(v=>v||0)}}).filter(s=>s.cAvg!=null||s.tAvg!=null);
 const mom=v=>v==null?'–':`<span class="${v>=0?'up':'dn'}">${v>=0?'▲':'▼'} ${Math.abs(v).toFixed(1)}%</span>`,dl=(a,b)=>a!=null&&b!=null?delta(a,b):delta(0,0);
 const trC=[{k:'name',h:'Store',v:s=>s.name},{k:'mm',h:'MM',v:s=>s.mm},{k:'cAvg',h:'Avg customers/day',n:1,v:s=>s.cAvg,r:s=>s.cAvg==null?'–':s.cAvg.toFixed(1)},{k:'tAvg',h:'Avg ticket/day',n:1,v:s=>s.tAvg,r:s=>s.tAvg==null?'–':'$'+s.tAvg.toFixed(2)},{k:'cLast',h:'Customers · '+M[idx[lastI]],n:1,v:s=>s.cLast,r:s=>s.cLast==null?'–':s.cLast.toFixed(1)},{k:'cMom',h:'MoM',n:1,v:s=>s.cMom,r:s=>mom(s.cMom)},{k:'tLast',h:'Ticket · '+M[idx[lastI]],n:1,v:s=>s.tLast,r:s=>s.tLast==null?'–':'$'+s.tLast.toFixed(2)},{k:'tMom',h:'MoM ',n:1,v:s=>s.tMom,r:s=>mom(s.tMom)},{k:'cs',h:'Customers trend',v:s=>s.cs.at(-1),r:s=>spark(s.cs)},{k:'ts',h:'Ticket trend',v:s=>s.ts.at(-1),r:s=>spark(s.ts)}];
 const TR=table('trf',trC,trL,r=>`<td>Average (${r.length})</td><td></td><td class="n">${(av(r.map(x=>x.cAvg))??0).toFixed(1)}</td><td class="n">$${(av(r.map(x=>x.tAvg))??0).toFixed(2)}</td><td></td><td></td><td></td><td></td><td></td><td></td>`);
 const best=[...trL].sort((a,b)=>(b.cLast||0)-(a.cLast||0))[0];
 $('#view').innerHTML=`<div class="view"><div class="bar">${range('s')}${mmSel}<div class="f">Search stores<input data-q placeholder="Store name…" value="${st.q}"></div><div class="chips" style="margin-left:auto">${['All','Last 3','Last 6'].map((c,i)=>`<span class="chip" data-qr="${i}">${c}</span>`).join('')}<span class="chip" data-reset>Reset</span></div></div>
 <div class="grid g4">${kpi('$','Total sales',sales$,'k',delta(F[lastI],F[lastI-1]))}${kpi('✦','Bonus disbursed',bon$,'k',`${sales$?(bon$/sales$*100).toFixed(2):0}% of sales`)}${kpi('▣','Active stores',act[lastI]||0,'n',`in ${M[idx[lastI]]}`)}${kpi('◔','Avg sales per store',act[lastI]?F[lastI]/act[lastI]:0,'k',`in ${M[idx[lastI]]}`)}</div>
 <div class="grid g2"><div class="card"><h3>Sales over time</h3><div class="sub">Final sales, projected sales and bonus paid by month</div><div class="ch"><canvas id="c1"></canvas></div></div><div class="card"><h3>Sales by MM</h3><div class="sub">Share of sales in selected period</div><div class="ch"><canvas id="c2"></canvas></div></div></div>
 <div class="grid g2e"><div class="card"><h3>Top 10 stores</h3><div class="sub">By sales in selected period</div><div class="ch"><canvas id="c3"></canvas></div></div><div class="card"><h3>Active stores &amp; average sales</h3><div class="sub">Store count growth against sales per store</div><div class="ch"><canvas id="c4"></canvas></div></div></div>
 <div class="hd"><h2>Month-wise summary</h2><button class="btn" data-exp="m">Export CSV</button></div><div class="card"><div class="tw"><table><thead><tr><th>Month</th><th class="n">Active stores</th><th class="n">Final sales</th><th class="n">Projected</th><th class="n">Bonus</th><th class="n">Bonus %</th><th class="n">MoM</th><th class="n">Avg store sales</th><th class="n">Avg customers/day</th><th class="n">Avg ticket/day</th><th>Top store</th></tr></thead><tbody>${rowsM}</tbody></table></div></div>
 <div class="hd"><h2>Store-wise sales</h2><button class="btn" data-exp="s">Export CSV</button></div><div class="card">${T.html}</div>
 <div class="hd"><h2>Customer traffic &amp; ticket size</h2><button class="btn" data-exp="t">Export CSV</button></div>
 <div class="grid g4">${kpi('☺','Avg customers / day',CU[lastI]||0,'d',dl(CU[lastI],CU[lastI-1]))}${kpi('$','Avg ticket / day',TK[lastI]||0,'t',dl(TK[lastI],TK[lastI-1]))}${kpi('▣','Stores reporting',trL.filter(s=>s.cLast!=null).length,'n','in '+M[idx[lastI]])}${kpi('★','Busiest store',best&&best.cLast||0,'d',best?best.name:'–')}</div>
 <div class="grid g2"><div class="card"><h3>Customers &amp; ticket trend</h3><div class="sub">Average across stores, by month</div><div class="ch"><canvas id="t1"></canvas></div></div><div class="card"><h3>Traffic vs ticket</h3><div class="sub">Each dot is a store (period average)</div><div class="ch"><canvas id="t4"></canvas></div></div></div>
 <div class="grid g2e"><div class="card"><h3>Top 10 stores: customers / day</h3><div class="sub">Period average</div><div class="ch"><canvas id="t2"></canvas></div></div><div class="card"><h3>Top 10 stores: ticket / day</h3><div class="sub">Period average</div><div class="ch"><canvas id="t3"></canvas></div></div></div>
 <div class="hd"><h2>Store-wise customers &amp; ticket</h2></div><div class="card">${TR.html}</div>
 <div class="hd"><h2>Targets vs projected</h2><div class="chips">${TM.map(i=>`<span class="chip ${ti===i?'on':''}" data-tm="${i}">${M[i]}</span>`).join('')}<span style="width:8px"></span>${['all','On target','Above max','Below target'].map(c=>`<span class="chip ${st.tstat===c?'on':''}" data-ts="${c}">${c==='all'?'All status':c}</span>`).join('')}</div></div>
 <div class="grid g4">${kpi('◎','Stores with targets',tl.length,'n',M[ti])}${kpi('✓','On or above target',cnt('On target')+cnt('Above max'),'n','projected ≥ min target')}${kpi('!','Below target',cnt('Below target'),'n','projected < min target')}${kpi('$','Projected vs min target',sum(tl.map(s=>s.proj)),'k',`min target ${K(sum(tl.map(s=>s.tmin)))}`)}</div>
 <div class="grid g2e"><div class="card"><h3>Target range vs projected</h3><div class="sub">Total across stores with a target</div><div class="ch s"><canvas id="c5"></canvas></div></div><div class="card"><h3>Target status</h3><div class="sub">${M[ti]} · stores by outcome</div><div class="ch s"><canvas id="c6"></canvas></div></div></div>
 <div class="card">${TT.html}</div><p class="mut" style="margin-top:14px;font-size:12px">Blank targets are treated as zero, so achievement is only scored for months with a target range (${TM.map(i=>M[i]).join(', ')}).</p></div>`;
 count();const lab=idx.map(i=>M[i]);
 chart('c1',{data:{labels:lab,datasets:[{type:'bar',label:'Final sales',data:F,backgroundColor:css('--pr'),borderRadius:6,order:2},{type:'line',label:'Projected',data:P.map(v=>v||null),borderColor:css('--or'),borderDash:[6,4],tension:.35,order:1,pointRadius:4},{type:'line',label:'Bonus (right)',data:B,borderColor:'#0e6b3a',yAxisID:'y2',tension:.35,order:1}]},options:{scales:{y2:{position:'right',grid:{display:false},ticks:{callback:v=>K(v)}}}}});
 chart('c2',{type:'doughnut',data:{labels:mmT.map(x=>x.m),datasets:[{data:mmT.map(x=>x.v),backgroundColor:PAL,borderWidth:0}]},options:{cutout:'62%',plugins:{legend:{position:'right',labels:{usePointStyle:true,boxWidth:8}},tooltip:{callbacks:{label:c=>`${c.label}: ${$$$(c.raw)}`}}}}});
 chart('c3',{type:'bar',data:{labels:top.map(s=>s.name.replace(/vape\s*time\s*-?\s*/i,'')),datasets:[{label:'Sales',data:top.map(s=>s.sales),backgroundColor:css('--pr'),borderRadius:6}]},options:{indexAxis:'y',plugins:{legend:{display:false}},scales:{x:{grid:{color:css('--bd')},ticks:{callback:v=>K(v)}},y:{grid:{display:false},ticks:{autoSkip:false}}}}});
 chart('c4',{data:{labels:lab,datasets:[{type:'line',label:'Active stores',data:act,borderColor:css('--pr'),backgroundColor:css('--pr')+'33',fill:true,tension:.35},{type:'line',label:'Avg store sales (right)',data:act.map((a,k)=>a?F[k]/a:0),borderColor:css('--or'),yAxisID:'y2',tension:.35}]},options:{scales:{y:{ticks:{callback:v=>v}},y2:{position:'right',grid:{display:false},ticks:{callback:v=>K(v)}}}}});
 chart('c5',{type:'bar',data:{labels:tmA.map(t=>M[t.i]),datasets:[{label:'Min target',data:tmA.map(t=>t.min),backgroundColor:css('--pr2'),borderRadius:6},{label:'Max target',data:tmA.map(t=>t.max),backgroundColor:css('--pr'),borderRadius:6},{label:'Projected',data:tmA.map(t=>t.p),backgroundColor:css('--or'),borderRadius:6}]}});
 chart('c6',{type:'doughnut',data:{labels:['On target','Above max','Below target'],datasets:[{data:[cnt('On target'),cnt('Above max'),cnt('Below target')],backgroundColor:['#84cc16','#1f9d55','#e5484d'],borderWidth:0}]},options:{cutout:'62%'}});

 const tA=[...trL].filter(s=>s.cAvg!=null).sort((a,b)=>b.cAvg-a.cAvg).slice(0,10),tB=[...trL].filter(s=>s.tAvg!=null).sort((a,b)=>b.tAvg-a.tAvg).slice(0,10);
 const hb=(id,arr,key,lbl,fmt)=>chart(id,{type:'bar',data:{labels:arr.map(s=>s.name.replace(/vape\\s*time\\s*-?\\s*/i,'')),datasets:[{label:lbl,data:arr.map(s=>s[key]),backgroundColor:css('--pr'),borderRadius:6}]},options:{indexAxis:'y',plugins:{legend:{display:false}},scales:{x:{grid:{color:css('--bd')},ticks:{callback:fmt}},y:{grid:{display:false},ticks:{autoSkip:false}}}}});
 chart('t1',{data:{labels:lab,datasets:[{type:'line',label:'Avg customers/day',data:CU,borderColor:css('--pr'),backgroundColor:css('--pr')+'33',fill:true,tension:.35,spanGaps:true},{type:'line',label:'Avg ticket/day (right)',data:TK,borderColor:css('--or'),yAxisID:'y2',tension:.35,spanGaps:true}]},options:{scales:{y:{grid:{color:css('--bd')},ticks:{callback:v=>v}},y2:{position:'right',grid:{display:false},ticks:{callback:v=>'$'+v}}}}});
 hb('t2',tA,'cAvg','Avg customers/day',v=>v);hb('t3',tB,'tAvg','Avg ticket/day',v=>'$'+v);
 chart('t4',{type:'scatter',data:{datasets:[{label:'Stores',data:trL.filter(s=>s.cAvg!=null&&s.tAvg!=null).map(s=>({x:s.cAvg,y:s.tAvg,n:s.name})),backgroundColor:css('--pr')+'cc',pointRadius:5,pointHoverRadius:8}]},options:{interaction:{mode:'nearest',intersect:true},plugins:{legend:{display:false},tooltip:{callbacks:{label:c=>`${c.raw.n}: ${c.raw.x.toFixed(1)} customers · $${c.raw.y.toFixed(2)}`}}},scales:{x:{type:'linear',title:{display:true,text:'Avg customers/day'},grid:{color:css('--bd')}},y:{title:{display:true,text:'Avg ticket/day ($)'},grid:{color:css('--bd')},ticks:{callback:v=>'$'+v}}}}});
 st._exp={m:[['Month','Active','Final','Projected','Bonus'],...idx.map((i,k)=>[M[i],act[k],F[k],P[k],B[k]])],t:[['Store','MM','Avg customers/day','Avg ticket/day'],...trL.map(s=>[s.name,s.mm,s.cAvg==null?'':s.cAvg.toFixed(2),s.tAvg==null?'':s.tAvg.toFixed(2)])],s:[['Store','MM','Sales','Bonus','Bonus %'],...T.rows.map(s=>[s.name,s.mm,s.sales.toFixed(2),s.bonus,s.bp.toFixed(2)])]}}
/* ---------- BONUS ---------- */
function bonus(){const idx=[...Array(st.bto-st.bfrom+1)].map((_,i)=>st.bfrom+i),sel=st.bmm.size?[...st.bmm]:MMS;
 const A=S.filter(s=>idx.some(i=>sel.includes(mgr(s,i)))),V=(s,i)=>sel.includes(mgr(s,i))?(s.mb[i]||0):0,vals=s=>idx.map(i=>V(s,i));
 const byM=idx.map(i=>sum(A.map(s=>V(s,i)))),paidN=idx.map(i=>A.filter(s=>V(s,i)>0).length),total=sum(byM);
 const mmR=sel.map(m=>{const mv=idx.map(i=>sum(S.filter(s=>mgr(s,i)===m).map(s=>s.mb[i]||0)));const x=S.filter(s=>idx.some(i=>mgr(s,i)===m));return{m,mv,t:sum(mv),n:x.filter(s=>idx.some(i=>mgr(s,i)===m&&s.mb[i]>0)).length,stores:x.length}}).filter(r=>r.stores).sort((a,b)=>b.t-a.t);
 const list=A.filter(match).map(s=>{const v=vals(s);return{...s,v,bonus:sum(v),paid:v.filter(x=>x>0).length,avg:v.filter(x=>x>0).length?sum(v)/v.filter(x=>x>0).length:0,max:Math.max(...v)}}).filter(s=>s.bonus>0);
 const cols=[{k:'name',h:'Store',v:s=>s.name},{k:'mm',h:'MM',v:s=>s.mm},{k:'bonus',h:'Total bonus',n:1,v:s=>s.bonus,r:s=>$$$(s.bonus)},{k:'paid',h:'Months paid',n:1,v:s=>s.paid},{k:'avg',h:'Avg / paid month',n:1,v:s=>s.avg,r:s=>$$$(s.avg)},{k:'max',h:'Highest month',n:1,v:s=>s.max,r:s=>$$$(s.max)},{k:'spk',h:'Trend',v:s=>s.v.at(-1),r:s=>spark(s.v)}];
 const T=table('bonus',cols,list,r=>`<td>Total (${r.length})</td><td></td><td class="n">${$$$(sum(r.map(x=>x.bonus)))}</td><td></td><td></td><td></td><td></td>`);
 const mx=Math.max(...mmR.flatMap(r=>r.mv),1),best=byM.indexOf(Math.max(...byM));
 const heat=`<div class="tw"><table><thead><tr><th>MM</th>${idx.map(i=>`<th class="n">${BM[i]}</th>`).join('')}<th class="n">Total</th><th class="n">Stores paid</th></tr></thead><tbody>${mmR.map(r=>`<tr><td>${r.m}</td>${r.mv.map(v=>`<td class="n" style="background:rgba(31,157,85,${(v/mx*.55).toFixed(2)})">${v?$$$(v):'–'}</td>`).join('')}<td class="n"><b>${$$$(r.t)}</b></td><td class="n">${r.n}/${r.stores}</td></tr>`).join('')}</tbody><tfoot><tr><td>All</td>${byM.map(v=>`<td class="n">${$$$(v)}</td>`).join('')}<td class="n">${$$$(total)}</td><td></td></tr></tfoot></table></div>`;
 $('#view').innerHTML=`<div class="view"><div class="bar">${range('b')}<div class="f">Search stores<input data-q placeholder="Store name…" value="${st.q}"></div><div class="f">Area MMs</div><div class="chips">${MMS.map(m=>`<span class="chip ${st.bmm.has(m)?'on':''}" data-bm="${m}">${m}</span>`).join('')}</div><div class="chips" style="margin-left:auto"><span class="chip" data-reset>Reset</span></div></div>
 <div class="grid g4">${kpi('$','Total bonus disbursed',total,'k',`${idx.length} months selected`)}${kpi('✦','Best month',byM[best]||0,'k',BM[idx[best]])}${kpi('☺','MMs paid',mmR.filter(r=>r.t>0).length,'n',`of ${mmR.length} in view`)}${kpi('▣','Stores paid (latest month)',paidN.at(-1)||0,'n',`avg ${paidN.at(-1)?$$$(byM.at(-1)/paidN.at(-1)):'$0'} per store`)}</div>
 <div class="grid g2"><div class="card"><h3>Monthly bonus disbursed</h3><div class="sub">Total payout and number of stores paid</div><div class="ch"><canvas id="b1"></canvas></div></div><div class="card"><h3>Bonus by MM</h3><div class="sub">Share of total payout</div><div class="ch"><canvas id="b2"></canvas></div></div></div>
 <div class="grid g2e"><div class="card"><h3>MM payouts by month</h3><div class="sub">Stacked by area MM</div><div class="ch"><canvas id="b3"></canvas></div></div><div class="card"><h3>Top 10 stores by bonus</h3><div class="sub">Total in selected period</div><div class="ch"><canvas id="b4"></canvas></div></div></div>
 <div class="hd"><h2>MM × month matrix</h2><button class="btn" data-exp="bm">Export CSV</button></div><div class="card">${heat}</div>
 <div class="hd"><h2>Store-wise bonus</h2><button class="btn" data-exp="bs">Export CSV</button></div><div class="card">${T.html}</div></div>`;
 count();const lab=idx.map(i=>BM[i]);
 chart('b1',{data:{labels:lab,datasets:[{type:'bar',label:'Bonus',data:byM,backgroundColor:css('--pr'),borderRadius:6},{type:'line',label:'Stores paid (right)',data:paidN,borderColor:css('--or'),yAxisID:'y2',tension:.35}]},options:{scales:{y2:{position:'right',grid:{display:false}}}}});
 chart('b2',{type:'doughnut',data:{labels:mmR.map(r=>r.m),datasets:[{data:mmR.map(r=>r.t),backgroundColor:PAL,borderWidth:0}]},options:{cutout:'62%',plugins:{legend:{position:'right',labels:{usePointStyle:true,boxWidth:8}}}}});
 chart('b3',{type:'bar',data:{labels:lab,datasets:mmR.map((r,i)=>({label:r.m,data:r.mv,backgroundColor:PAL[i%PAL.length]}))},options:{scales:{x:{stacked:true,grid:{display:false}},y:{stacked:true,grid:{color:css('--bd')},ticks:{callback:v=>K(v)}}}}});
 const t10=[...list].sort((a,b)=>b.bonus-a.bonus).slice(0,10);
 chart('b4',{type:'bar',data:{labels:t10.map(s=>s.name.replace(/vape\s*time\s*-?\s*/i,'')),datasets:[{label:'Bonus',data:t10.map(s=>s.bonus),backgroundColor:css('--pr'),borderRadius:6}]},options:{indexAxis:'y',plugins:{legend:{display:false}},scales:{x:{grid:{color:css('--bd')},ticks:{callback:v=>K(v)}},y:{grid:{display:false},ticks:{autoSkip:false}}}}});
 st._exp={bm:[['MM',...lab,'Total'],...mmR.map(r=>[r.m,...r.mv,r.t])],bs:[['Store','MM','Total bonus','Months paid'],...T.rows.map(s=>[s.name,s.mm,s.bonus,s.paid])]}}
/* ---------- STORE MODAL ---------- */
function modal(id){const s=S[id],f=s.mo.map(m=>m.f),b=s.mo.map(m=>m.b),p=s.mo.map(m=>m.p||null);
 $('#mb').innerHTML=`<h2>${s.name}</h2><p class="mut">MM: ${s.mm}</p><div class="grid g4" style="margin-top:14px">${kpi('$','Total sales',sum(f),'k',M[0]+' – '+M.at(-1))}${kpi('✦','Bonus disbursed',sum(b),'k','disbursed')}${kpi('▲','Best month',Math.max(...f),'k',M[f.indexOf(Math.max(...f))])}${kpi('◎',M[st.tm]+' target',tg(s.mo[st.tm].t)?.[0]||0,'k',tg(s.mo[st.tm].t)?'min of '+K(s.mo[st.tm].t[0])+' – '+K(s.mo[st.tm].t[1]):'no target set')}</div><div class="card"><div class="ch s"><canvas id="m1"></canvas></div></div>
 <div class="tw" style="margin-top:14px"><table><thead><tr><th>Month</th><th class="n">Target</th><th class="n">Projected</th><th class="n">Final sales</th><th class="n">Bonus</th><th class="n">Customers/day</th><th class="n">Ticket/day</th></tr></thead><tbody>${s.mo.map((m,i)=>`<tr><td>${M[i]}</td><td class="n">${tg(m.t)?K(m.t[0])+' – '+K(m.t[1]):'–'}</td><td class="n">${m.p?$$$(m.p):'–'}</td><td class="n">${m.f?$$$(m.f):'–'}</td><td class="n">${m.b?$$$(m.b):'–'}</td><td class="n">${m.c?m.c.toFixed(1):'–'}</td><td class="n">${m.tk?'$'+m.tk.toFixed(2):'–'}</td></tr>`).join('')}</tbody></table></div>`;
 $('#modal').hidden=false;count();chart('m1',{data:{labels:M,datasets:[{type:'bar',label:'Final sales',data:f,backgroundColor:css('--pr'),borderRadius:6},{type:'line',label:'Projected',data:p,borderColor:css('--or'),borderDash:[6,4],pointRadius:4},{type:'line',label:'Bonus (right)',data:b,borderColor:'#0e6b3a',yAxisID:'y2'}]},options:{scales:{y2:{position:'right',grid:{display:false}}}}})}
/* ---------- CORE ---------- */
function render(){charts.forEach(c=>c.destroy());charts=[];$('#title').textContent=st.page==='sales'?'Targets & Sales':'Bonus Payouts';$$('nav a').forEach(a=>a.classList.toggle('on',a.dataset.p===st.page));st.page==='sales'?sales():bonus()}
document.addEventListener('click',e=>{const t=e.target.closest('[data-t],[data-pg],[data-qr],[data-reset],[data-tm],[data-ts],[data-bm],[data-exp],[data-s],[data-p]');if(!t)return;const d=t.dataset;
 if(d.t){const s=st.sort[d.t];st.sort[d.t]=[d.k,s[0]===d.k?-s[1]:-1]}else if(d.pg){st.pg[d.pg]=Math.max(0,st.pg[d.pg]+ +d.d)}
 else if(d.qr!==undefined){if(+d.qr===0){st.from=0;st.to=M.length-1}else{st.to=LAST;st.from=Math.max(0,LAST-[0,3,6][d.qr]+1)}}
 else if(d.reset!==undefined){Object.assign(st,{from:0,to:M.length-1,mm:'all',q:'',gq:'',tstat:'all',bmm:new Set(),bfrom:0,bto:BM.length-1,tm:defTm()});$('#gq').value=''}
 else if(d.tm){st.tm=+d.tm}else if(d.ts){st.tstat=d.ts}else if(d.bm){st.bmm.has(d.bm)?st.bmm.delete(d.bm):st.bmm.add(d.bm)}
 else if(d.exp){csv(st._exp[d.exp],d.exp+'.csv');return}else if(d.s!==undefined){modal(+d.s);return}else if(d.p){st.page=d.p;st.q='';st.pg={sales:0,bonus:0,tgt:0,trf:0}}
 render()});
document.addEventListener('change',e=>{const t=e.target,d=t.dataset;if(d.r){const v=+t.value;({sf:()=>st.from=v,st:()=>st.to=v,bf:()=>st.bfrom=v,bt:()=>st.bto=v})[d.r]();if(st.from>st.to)st.to=st.from;if(st.bfrom>st.bto)st.bto=st.bfrom}else if(d.mm!==undefined)st.mm=t.value;else return;render()});
let tm;document.addEventListener('input',e=>{if(e.target.matches('[data-q]')||e.target.id==='gq'){e.target.id==='gq'?st.gq=e.target.value:st.q=e.target.value;st.pg={sales:0,bonus:0,tgt:0,trf:0};clearTimeout(tm);tm=setTimeout(()=>{render();const i=$('[data-q]');if(i&&e.target.id!=='gq'){i.focus();i.setSelectionRange(99,99)}},180)}});
function theme(t){document.documentElement.dataset.theme=t;localStorage.setItem('theme',t);$('#theme').textContent=t==='dark'?'☀':'☾';if(!$('#app').hidden)render()}
$('#theme').onclick=()=>theme(document.documentElement.dataset.theme==='dark'?'light':'dark');theme(document.documentElement.dataset.theme);
$('#collapse').onclick=()=>{$('#app').classList.toggle('collapsed');localStorage.setItem('col',$('#app').classList.contains('collapsed')?1:'')};
$('#mx').onclick=()=>{$('#modal').hidden=true;render()};$('#modal').onclick=e=>{if(e.target.id==='modal')$('#mx').click()};
const tok=()=>sessionStorage.getItem('tk');
function init(d){M=d.months;BM=d.bmonths;S=d.stores.map(s=>{const mm=s.mm&&s.mm!=='_'?s.mm:'Unassigned';return{...s,mm,mms:(s.mms||[]).map(x=>x&&x!=='_'?x:mm)}});MMS=[...new Set(S.flatMap(s=>[s.mm,...s.mms]))].sort();
 TM=M.map((_,i)=>i).filter(i=>S.some(s=>tg(s.mo[i].t)));LAST=0;M.forEach((_,i)=>{if(S.some(s=>s.mo[i].f>0))LAST=i});
 Object.assign(st,{from:0,to:M.length-1,bfrom:0,bto:BM.length-1,tm:defTm(),mm:'all',q:'',gq:'',bmm:new Set(),tstat:'all',bmm:new Set()});$('#upd').textContent='Updated '+new Date(d.updated).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}
async function load(){const r=await fetch('/api/data',{headers:{Authorization:'Bearer '+tok()}});if(r.status===401)return $('#logout').click();const d=await r.json();if(!r.ok)throw new Error(d.error||'Could not load data');init(d)}
async function go(){$('#view').innerHTML='<div class="card empty">Loading data from Google Sheets…</div>';try{await load();render()}catch(e){$('#view').innerHTML=`<div class="card empty"><b>Could not load the data.</b><br>${e.message}<br><br><button class="btn primary" id="retry">Try again</button></div>`;$('#retry').onclick=go}}
function enter(){$('#login').hidden=true;$('#app').hidden=false;if(localStorage.getItem('col'))$('#app').classList.add('collapsed');go()}
$('#ref').onclick=async()=>{$('#ref').classList.add('spin');await go();$('#ref').classList.remove('spin')};
$('#lf').onsubmit=async e=>{e.preventDefault();const b=$('#lf button');b.disabled=true;$('#err').textContent='';
 try{const r=await fetch('/api/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({u:$('#u').value.trim(),p:$('#p').value})});const d=await r.json();if(!r.ok)throw new Error(d.error);sessionStorage.setItem('tk',d.token);enter()}
 catch(x){$('#err').textContent=x.message;$('#lf').classList.remove('shake');void $('#lf').offsetWidth;$('#lf').classList.add('shake')}b.disabled=false};
$('#logout').onclick=()=>{sessionStorage.removeItem('tk');location.reload()};
if(tok())enter();
